/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlbaiguixe;

import Bean.DanhMuc;
import Controller.ConTroller;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author hthkt
 */
public class MainFrame extends javax.swing.JFrame {

    /**^
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setTitle("QL bai do xe");
        
        ConTroller ct = new ConTroller(jpnView);
        ct.setView(jpnNhanXe,NhanXe );
        
        List<DanhMuc> listItem = new ArrayList<>();
        listItem.add(new DanhMuc("TraXe", jpnTraXe, TraXe));
        listItem.add(new DanhMuc("NhanXe", jpnNhanXe, NhanXe));
        listItem.add(new DanhMuc("ThongTin", jpnThongKe, ThongKe));
        listItem.add(new DanhMuc("DKVeThang",jpnDKVeThang, DKVeThang));
        listItem.add(new DanhMuc("TraCuu", jpnTraCuu, TraCuu));

        ct.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnt = new javax.swing.JPanel();
        JpnMenu = new javax.swing.JPanel();
        jpnNhanXe = new javax.swing.JPanel();
        NhanXe = new javax.swing.JLabel();
        jpnTraXe = new javax.swing.JPanel();
        TraXe = new javax.swing.JLabel();
        jpnDKVeThang = new javax.swing.JPanel();
        DKVeThang = new javax.swing.JLabel();
        jpnTraCuu = new javax.swing.JPanel();
        TraCuu = new javax.swing.JLabel();
        jpnThongKe = new javax.swing.JPanel();
        ThongKe = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnt.setBackground(new java.awt.Color(255, 255, 255));

        JpnMenu.setBackground(new java.awt.Color(185, 211, 238));

        jpnNhanXe.setBackground(new java.awt.Color(255, 255, 255));

        NhanXe.setBackground(new java.awt.Color(255, 255, 255));
        NhanXe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NhanXe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NhanXe.setText("Nhận xe");
        NhanXe.setPreferredSize(new java.awt.Dimension(124, 20));

        javax.swing.GroupLayout jpnNhanXeLayout = new javax.swing.GroupLayout(jpnNhanXe);
        jpnNhanXe.setLayout(jpnNhanXeLayout);
        jpnNhanXeLayout.setHorizontalGroup(
            jpnNhanXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NhanXe, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jpnNhanXeLayout.setVerticalGroup(
            jpnNhanXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NhanXe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpnTraXe.setBackground(new java.awt.Color(255, 255, 255));

        TraXe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TraXe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TraXe.setText("Trả xe");
        TraXe.setPreferredSize(new java.awt.Dimension(124, 20));

        javax.swing.GroupLayout jpnTraXeLayout = new javax.swing.GroupLayout(jpnTraXe);
        jpnTraXe.setLayout(jpnTraXeLayout);
        jpnTraXeLayout.setHorizontalGroup(
            jpnTraXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTraXeLayout.createSequentialGroup()
                .addComponent(TraXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnTraXeLayout.setVerticalGroup(
            jpnTraXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TraXe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpnDKVeThang.setBackground(new java.awt.Color(255, 255, 255));

        DKVeThang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DKVeThang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DKVeThang.setText("Đăng ký vé tháng");
        DKVeThang.setPreferredSize(new java.awt.Dimension(124, 20));

        javax.swing.GroupLayout jpnDKVeThangLayout = new javax.swing.GroupLayout(jpnDKVeThang);
        jpnDKVeThang.setLayout(jpnDKVeThangLayout);
        jpnDKVeThangLayout.setHorizontalGroup(
            jpnDKVeThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DKVeThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnDKVeThangLayout.setVerticalGroup(
            jpnDKVeThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DKVeThang, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
        );

        jpnTraCuu.setBackground(new java.awt.Color(255, 255, 255));

        TraCuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TraCuu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TraCuu.setText("Tra cứu");
        TraCuu.setPreferredSize(new java.awt.Dimension(124, 20));

        javax.swing.GroupLayout jpnTraCuuLayout = new javax.swing.GroupLayout(jpnTraCuu);
        jpnTraCuu.setLayout(jpnTraCuuLayout);
        jpnTraCuuLayout.setHorizontalGroup(
            jpnTraCuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTraCuuLayout.createSequentialGroup()
                .addComponent(TraCuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnTraCuuLayout.setVerticalGroup(
            jpnTraCuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TraCuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ThongKe.setBackground(new java.awt.Color(255, 255, 255));
        ThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ThongKe.setText("Thống kê");

        javax.swing.GroupLayout jpnThongKeLayout = new javax.swing.GroupLayout(jpnThongKe);
        jpnThongKe.setLayout(jpnThongKeLayout);
        jpnThongKeLayout.setHorizontalGroup(
            jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        jpnThongKeLayout.setVerticalGroup(
            jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JpnMenuLayout = new javax.swing.GroupLayout(JpnMenu);
        JpnMenu.setLayout(JpnMenuLayout);
        JpnMenuLayout.setHorizontalGroup(
            JpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnNhanXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnTraXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnDKVeThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnTraCuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );
        JpnMenuLayout.setVerticalGroup(
            JpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnDKVeThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnTraXe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnNhanXe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnTraCuu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpnView.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpntLayout = new javax.swing.GroupLayout(jpnt);
        jpnt.setLayout(jpntLayout);
        jpntLayout.setHorizontalGroup(
            jpntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpntLayout.setVerticalGroup(
            jpntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpntLayout.createSequentialGroup()
                .addComponent(JpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DKVeThang;
    private javax.swing.JPanel JpnMenu;
    private javax.swing.JLabel NhanXe;
    private javax.swing.JLabel ThongKe;
    private javax.swing.JLabel TraCuu;
    private javax.swing.JLabel TraXe;
    private javax.swing.JPanel jpnDKVeThang;
    private javax.swing.JPanel jpnNhanXe;
    private javax.swing.JPanel jpnThongKe;
    private javax.swing.JPanel jpnTraCuu;
    private javax.swing.JPanel jpnTraXe;
    private javax.swing.JPanel jpnView;
    private javax.swing.JPanel jpnt;
    // End of variables declaration//GEN-END:variables
}
