/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.qlbaiguixe;

import Controller.Date;
import Controller.Time;
import ThongBao.DatabaseLink;
import ThongBao.KTraLoi;
import ThongBao.ThongBaoHL;
import com.mycompany.qlbaiguixe.model.VE;
import com.mycompany.qlbaiguixe.model.VAOBEN;
import com.mycompany.qlbaiguixe.model.VETHANG;
import com.mycompany.qlbaiguixe.model.VETHANGDAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author hthkt
 */
public class NhanXeJPanel extends javax.swing.JPanel {
    private MainFrame parentForm;
    private ArrayList<VAOBEN> list = new ArrayList<>();
    DefaultTableModel model;

    /**
     * Creates new form QLTheJPanel
     */
    public NhanXeJPanel() {
                initComponents();
        initTime();
        initDate();
        //showLV();

        showCBB("Vé ngày");
        showKV("KHUVUC");
    }

    private void initTime() {
        Time t = new Time(GioVao);
        t.start();
    }
    private void initDate(){
        Date d = new Date(Ngayvao);
        d.start();
     }
    /*private void showResult() {
        RAVAOBEN rvb = list.get(list.size()-1);
        model.addRow(new Object[]{
         rvb.getMAVE(),rvb.getLOAIVE(),rvb.getTENKHUVUC(),rvb.getBIENSOXE(),rvb.getTHOIGIANVAO(),rvb.getTHOIGIANRA(),rvb.getTINHTRANGVE()
         });
    }*/
    synchronized private void showCBB(String loaiVe) {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://LAPTOP-TOSHQ4P7\\SQLEXPRESS:1433;database=QLBAIDOXE;user = sa;password = 12;encrypt = false");
            String sql = "SELECT MAVE FROM dbo.VE where LOAIVE = N'%s' ".formatted(loaiVe);
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            txtMaVe.removeAllItems();
            while (rs.next()) {
                txtMaVe.addItem(rs.getString("MAVE"));
            }
            rs.close();
            ps.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void showKV(String kv){
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://LAPTOP-TOSHQ4P7\\SQLEXPRESS:1433;database=QLBAIDOXE;user = sa;password = 12;encrypt = false");
            String sql = "SELECT TENKHUVUC FROM dbo.%s".formatted(kv);
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            txtKhuVuc.removeAllItems();
            
            while (rs.next()) {                
                txtKhuVuc.addItem(rs.getString("TENKHUVUC"));
            }
            rs.close();
            ps.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    public void showLV(){
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://LAPTOP-TOSHQ4P7\\SQLEXPRESS:1433;database=QLBAIDOXE;user = sa;password = 12;encrypt = false");
            String sql = "SELECT DISTINCT LOAIVE FROM dbo.VAOBEN";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            LoaiVe.removeAllItems();
            while (rs.next()) {                
                LoaiVe.addItem(rs.getString("LOAIVE"));
            }
            rs.close();
            ps.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jpnLoaiVe = new javax.swing.JLabel();
        LoaiVe = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtbsx = new javax.swing.JLabel();
        txtkv = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaVe = new javax.swing.JComboBox<>();
        txtBSX = new javax.swing.JTextField();
        txtKhuVuc = new javax.swing.JComboBox<>();
        Save = new javax.swing.JButton();
        GioVao = new javax.swing.JLabel();
        Ngayvao = new javax.swing.JLabel();
        GiaTien = new javax.swing.JLabel();
        txtGiaTien = new javax.swing.JTextField();

        jpnLoaiVe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jpnLoaiVe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpnLoaiVe.setText("Loại Vé:");

        LoaiVe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vé ngày", "Vé tháng" }));
        LoaiVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoaiVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jpnLoaiVe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpnLoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã vé:");

        txtbsx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtbsx.setText("Biển số xe:");

        txtkv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtkv.setText("Khu vực:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày vào:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Giờ vào:");

        txtMaVe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtMaVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaVeActionPerformed(evt);
            }
        });

        txtBSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBSXActionPerformed(evt);
            }
        });

        txtKhuVuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhuVucActionPerformed(evt);
            }
        });

        Save.setText("Xác nhận");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        GioVao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GioVao.setText("8:8:8 PM");

        Ngayvao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Ngayvao.setText("18-10-2002");

        GiaTien.setText("Giá tiền:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtbsx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtkv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBSX)
                            .addComponent(txtKhuVuc, 0, 123, Short.MAX_VALUE)
                            .addComponent(txtMaVe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(GiaTien)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GioVao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ngayvao, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txtGiaTien)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(txtMaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ngayvao))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbsx)
                    .addComponent(jLabel5)
                    .addComponent(txtBSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GioVao))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkv)
                    .addComponent(txtKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LoaiVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoaiVeActionPerformed
        // TODO add your handling code here:
        try {

            String option = (String) this.LoaiVe.getSelectedItem();
            VETHANGDAO data = new VETHANGDAO();
            if (option.equals("Vé ngày")) {
                txtBSX.setEnabled(true);
                txtKhuVuc.setEnabled(true);
                txtGiaTien.setEnabled(true);
                showCBB("Vé ngày");
                showKV("KHUVUC");
            } else {
                txtBSX.setEnabled(false);
                txtKhuVuc.setEnabled(false);
                txtGiaTien.setEnabled(false);
                showCBB("Vé tháng");
                //showKV("KHUVUC");
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }                           
        
         
        
        
        
    }//GEN-LAST:event_LoaiVeActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        String id = (String) txtMaVe.getSelectedItem();
        String nb = txtBSX.getText();
        VAOBEN rvb = new VAOBEN();
        var giovao = GioVao.getText().split(" ")[0];
        rvb.setTHOIGIANVAO(Ngayvao.getText() + " " + giovao);

        rvb.setBIENSOXE(txtBSX.getText());
        rvb.setMAVE((String) txtMaVe.getSelectedItem());
        rvb.setLOAIVE((String) LoaiVe.getSelectedItem());
        rvb.setTENKHUVUC((String) txtKhuVuc.getSelectedItem());
        rvb.setGIATIEN(txtGiaTien.getText());
        
        if (new DatabaseLink().addVAOBEN(rvb)) {
            JOptionPane.showMessageDialog(parentForm, "Xác Nhận Thành Công");
            list.add(rvb);
            
        } else {
            JOptionPane.showMessageDialog(parentForm, "Vé đã được sử dụng hoặc không hợp lệ");
        }
      
       // showResult();
        
    }//GEN-LAST:event_SaveActionPerformed

    private void txtMaVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaVeActionPerformed
        // TODO add your handling code here:
        if (this.txtMaVe.getSelectedItem() != null && this.LoaiVe.getSelectedItem().equals("Vé tháng")) {
            String maVe = (String) this.txtMaVe.getSelectedItem();
            VETHANGDAO vtVethangdao = new VETHANGDAO();
            var vt = vtVethangdao.findByIDVe(maVe);
            this.txtBSX.setText(vt.getBIENSOXE());
            this.txtKhuVuc.removeAllItems();
            this.txtKhuVuc.addItem(vt.getTENKHUVUC());
            this.txtGiaTien.setText(vt.getSOTIEN());
        }
        else if(this.txtMaVe.getSelectedItem() != null && this.LoaiVe.getSelectedItem().equals("Vé ngày")){
            String maVe = (String) this.txtMaVe.getSelectedItem();
            VETHANGDAO vtVethangdao = new VETHANGDAO();
            var vt = vtVethangdao.findByIDVe(maVe);
            this.txtBSX.setText("");
            this.txtGiaTien.setText("");
            
        }
        
    }//GEN-LAST:event_txtMaVeActionPerformed

    private void txtKhuVucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhuVucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKhuVucActionPerformed

    private void txtBSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBSXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBSXActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GiaTien;
    private javax.swing.JLabel GioVao;
    private javax.swing.JComboBox<String> LoaiVe;
    private javax.swing.JLabel Ngayvao;
    private javax.swing.JButton Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jpnLoaiVe;
    private javax.swing.JTextField txtBSX;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JComboBox<String> txtKhuVuc;
    private javax.swing.JComboBox<String> txtMaVe;
    private javax.swing.JLabel txtbsx;
    private javax.swing.JLabel txtkv;
    // End of variables declaration//GEN-END:variables


}
