/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.qlbaiguixe;

import ThongBao.DBConnection;
import ThongBao.DatabaseLink;
import ThongBao.ThongBaoHL;
import com.mycompany.qlbaiguixe.model.TRAXE;
import com.mycompany.qlbaiguixe.model.TRAXEDAO;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hthkt
 */
public class TraXeJPanel extends javax.swing.JPanel {
//    private DefaultTableModel tbl;
//    private MainFrame preFrom ;
//    

    /**
     * Creates new form QLVeJPanel
     */
    public TraXeJPanel() {
        initComponents();
        showDuLieu();
        initDate();
    }
    private void initDate(){
        Controller.Date d = new Controller.Date(NgayRa);
        d.start();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfTimKiem = new javax.swing.JTextField();
        JCBMAVEBS = new javax.swing.JComboBox<>();
        JBTimKiem = new javax.swing.JButton();
        JBTraXe = new javax.swing.JButton();
        JBThemXe = new javax.swing.JButton();
        JBCapNhat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfMaVe = new javax.swing.JTextField();
        tfLoaiVe = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BangDL = new javax.swing.JTable();
        tfBienSo = new javax.swing.JTextField();
        tfKhuVuc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfNgayGioVao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NgayRa = new javax.swing.JLabel();
        Tien = new javax.swing.JLabel();
        txtTien = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tìm kiếm thông tin xe:");

        tfTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTimKiemActionPerformed(evt);
            }
        });

        JCBMAVEBS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JCBMAVEBS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Vé", "Biển Số Xe" }));
        JCBMAVEBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBMAVEBSActionPerformed(evt);
            }
        });

        JBTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JBTimKiem.setText("Tìm kiếm");
        JBTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTimKiemActionPerformed(evt);
            }
        });

        JBTraXe.setText("Trả Xe");
        JBTraXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTraXeActionPerformed(evt);
            }
        });

        JBThemXe.setText("Làm Mới");
        JBThemXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBThemXeActionPerformed(evt);
            }
        });

        JBCapNhat.setText("Cập Nhật");
        JBCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCBMAVEBS, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JBTraXe)
                        .addGap(18, 18, 18)
                        .addComponent(JBThemXe)
                        .addGap(18, 18, 18)
                        .addComponent(JBCapNhat)))
                .addGap(18, 18, 18)
                .addComponent(JBTimKiem)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBMAVEBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTraXe)
                    .addComponent(JBThemXe)
                    .addComponent(JBCapNhat)))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Biển số xe:");

        tfMaVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaVeActionPerformed(evt);
            }
        });

        tfLoaiVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLoaiVeActionPerformed(evt);
            }
        });

        jPanel3.setLayout(new java.awt.BorderLayout());

        BangDL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã vé", "Loại vé", "Biển số xe", "Khu vực", "Ngày Giờ nhận"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(BangDL);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tfKhuVuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKhuVucActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mã Vé");

        jLabel6.setText("Loại Vé");

        jLabel7.setText("Khu Vực");

        tfNgayGioVao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNgayGioVaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Ngày Giờ Vào:");

        jLabel5.setText("Ngày Ra:");

        NgayRa.setText("18-10-2002");

        Tien.setText("Gía tiền:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfLoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(tfKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(tfBienSo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tfNgayGioVao, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(146, 213, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NgayRa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTien, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfMaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfBienSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfNgayGioVao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfLoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(tfKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel8)
                                .addComponent(NgayRa)))
                        .addGap(26, 26, 26)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tien, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

//    private void formComponenShow(java.awt.event.ComponentEvent evt){
//      //  showDuLieu();
//    }

    private void JBTraXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTraXeActionPerformed
       // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Bạn muốn trả xe?");
        int posittion = 0;
        if (result == 0) {
            posittion = BangDL.getSelectedRow();
            String data = null;
            if (posittion == -1) {
                data = this.tfMaVe.getText();
            } else {
                data = BangDL.getModel().getValueAt(posittion, 0).toString();
//                BangDL.getSelectionModel().addSelectionInterval(posittion, 0);
            }

            System.out.println(data);

            try {
                Connection connection = DBConnection.getConnection();
                String query = "DELETE FROM dbo.VAOBEN WHERE MAVE = ?";
                PreparedStatement ps = connection.prepareStatement(query);
                ps.setString(1, data);
                ps.executeUpdate();
                showDuLieu();
                DBConnection.closeConnection(connection);
                JOptionPane.showMessageDialog(null, "Trả thành công");
                            TRAXE trxe2 = new TRAXE();
            trxe2.setMAVE(tfMaVe.getText());
            trxe2.setLOAIVE(tfLoaiVe.getText());
            trxe2.setBIENSO(tfBienSo.getText());
            trxe2.setKHUVUC(tfKhuVuc.getText());
            trxe2.setTHOIGIANRA(NgayRa.getText());
            trxe2.setSOTIEN(txtTien.getText());

            TRAXEDAO dao = new TRAXEDAO();
            dao.insert(trxe2);

            JOptionPane.showMessageDialog(this, "Xe đã được lưu lại CSDL");
            showDuLieu();
            } catch (SQLException ex) {
                ex.printStackTrace();
            } catch (Exception ex) {
                Logger.getLogger(TraXeJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        //--------------------------------------------
//        StringBuilder sb2 = new StringBuilder();
//        try {
//            TRAXE trxe2 = new TRAXE();
//            trxe2.setMAVE(tfMaVe.getText());
//            trxe2.setLOAIVE(tfLoaiVe.getText());
//            trxe2.setBIENSO(tfBienSo.getText());
//            trxe2.setKHUVUC(tfKhuVuc.getText());
//            trxe2.setTHOIGIANRA(NgayRa.getText());
//            trxe2.setSOTIEN(txtTien.getText());
//
//            TRAXEDAO dao = new TRAXEDAO();
//            dao.insert(trxe2);
//
//            JOptionPane.showMessageDialog(this, "Xe đã được lưu lại CSDL");
//            showDuLieu();
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "error:" + e.getLocalizedMessage());
//            e.printStackTrace();
//        }
        
//-------------------------------------
//     StringBuilder sb = new StringBuilder();
//        if (tfMaVe.getText().equals("")) {
//            sb.append("Ma ve ko dc de trong");
//            tfMaVe.setBackground(Color.red);
//        } else {
//            tfMaVe.setBackground(Color.WHITE);
//        }
//        if (sb.length() > 0) {
//            JOptionPane.showMessageDialog(this, sb);
//            return;
//        }
//        try {
//            TRAXE trxe = new TRAXE();
//            trxe.setMAVE(tfMaVe.getText());
//            trxe.setLOAIVE(tfLoaiVe.getText());
//            trxe.setBIENSO(tfBienSo.getText());
//            trxe.setKHUVUC(tfKhuVuc.getText());
//            trxe.setTHOIGIANVAO(tfNgayGioVao.getText());
//            // trxe.setNGAYGIOVAO(tfNgayGioVao.getText());
//
//            TRAXEDAO dao = new TRAXEDAO();
//            dao.xoaxe(trxe);
//
//            JOptionPane.showMessageDialog(this, "xe đã được xóa khỏi bến");
//            showDuLieu();
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "error:" + e.getLocalizedMessage());
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_JBTraXeActionPerformed

    private void JCBMAVEBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBMAVEBSActionPerformed
        // TODO add your handling code here:
        //cách 1 lấy trục tiếp không qua index
        String selectedItem = (String) JCBMAVEBS.getSelectedItem();
        System.out.println("lua chon cua ban:" + selectedItem);
        //cách 2 thông qua index

    }//GEN-LAST:event_JCBMAVEBSActionPerformed

    private void tfKhuVucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKhuVucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKhuVucActionPerformed

    private void JBThemXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBThemXeActionPerformed
        // TODO add your handling code here:
        tfTimKiem.setText("");
        tfMaVe.setText("");
        tfLoaiVe.setText("");
        tfBienSo.setText("");
        tfKhuVuc.setText("");
        tfNgayGioVao.setText("");
        txtTien.setText("");
    }//GEN-LAST:event_JBThemXeActionPerformed

    private void JBTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTimKiemActionPerformed
// TODO add your handling code here:
// if(selectedItem ==  ){
//            
//                     }
        if (tfTimKiem.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn cần phải nhập mã vé");
            return;
        }
        try {

            String option = (String) this.JCBMAVEBS.getSelectedItem();
            TRAXEDAO dao2 = new TRAXEDAO();
            if (option.equals("Mã Vé")) {
                TRAXE traxe3 = dao2.finById(tfTimKiem.getText());
                if (traxe3 != null) {
                    tfMaVe.setText(traxe3.getMAVE());
                    tfLoaiVe.setText(traxe3.getLOAIVE());
                    tfBienSo.setText(traxe3.getBIENSO());
                    tfKhuVuc.setText(traxe3.getKHUVUC());
                    tfNgayGioVao.setText(traxe3.getTHOIGIANRA());
                    txtTien.setText(traxe3.getSOTIEN());

                } else {
                    JOptionPane.showMessageDialog(this, "Vé này không tồn tại trên hệ thống");
                }
            } else if (option.equals("Biển Số Xe")) {
                TRAXE traxe3 = dao2.findByLicencePlate(tfTimKiem.getText());
                if (traxe3 != null) {
                    tfMaVe.setText(traxe3.getMAVE());
                    tfLoaiVe.setText(traxe3.getLOAIVE());
                    tfBienSo.setText(traxe3.getBIENSO());
                    tfKhuVuc.setText(traxe3.getKHUVUC());
                    tfNgayGioVao.setText(traxe3.getTHOIGIANRA());
                    txtTien.setText(traxe3.getSOTIEN());
                    

                } else {
                    JOptionPane.showMessageDialog(this, "Không tồn tại xe này trên Hệ thống");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error:" + e.getLocalizedMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_JBTimKiemActionPerformed

    private void tfNgayGioVaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNgayGioVaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNgayGioVaoActionPerformed

    private void JBCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCapNhatActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if (tfMaVe.getText().equals("")) {
            sb.append("Ma ve ko dc de trong");
            tfMaVe.setBackground(Color.red);
        } else {
            tfMaVe.setBackground(Color.WHITE);
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb);
            return;
        }
        try {
            TRAXE trxe = new TRAXE();
            trxe.setMAVE(tfMaVe.getText());
            trxe.setLOAIVE(tfLoaiVe.getText());
            trxe.setBIENSO(tfBienSo.getText());
            trxe.setKHUVUC(tfKhuVuc.getText());
            trxe.setTHOIGIANRA(tfNgayGioVao.getText());
            trxe.setSOTIEN(txtTien.getText());

            TRAXEDAO dao = new TRAXEDAO();
            dao.update(trxe);

            JOptionPane.showMessageDialog(this, "xe đã được cập nhật vào bến");
            showDuLieu();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error:" + e.getLocalizedMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_JBCapNhatActionPerformed

    private void tfTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTimKiemActionPerformed

    private void tfMaVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaVeActionPerformed
        // TODO add your handling code here:
        StringBuilder sb2 = new StringBuilder();
        if (tfMaVe.getText().equals("")) {
            sb2.append("Ma ve ko dc de trong");
            tfMaVe.setBackground(Color.red);
        } else {
            tfMaVe.setBackground(Color.WHITE);
        }
        if (sb2.length() > 0) {
            JOptionPane.showMessageDialog(this, sb2);
            return;
        }
    }//GEN-LAST:event_tfMaVeActionPerformed

    private void tfLoaiVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLoaiVeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLoaiVeActionPerformed
    private void showDuLieu() {
        try {
            ((DefaultTableModel) BangDL.getModel()).setRowCount(0);
            String[] arr = {"Mã vé", "Loại vé", "Biển số xe", "Khu vực", "Ngày Giờ nhận","Gía tiền"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);
            Connection connection = DBConnection.getConnection();
            String query = "SELECT VE.MAVE, VE.LOAIVE, VAOBEN.BIENSOXE, VAOBEN.TENKHUVUC, VAOBEN.THOIGIANVAO,VAOBEN.SOTIEN FROM VE RIGHT JOIN VAOBEN ON VE.MAVE=VAOBEN.MAVE";
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {

                model.addRow(new String[]{rs.getString("MAVE"),
                    rs.getString("LOAIVE"), rs.getString("BIENSOXE"),
                    rs.getString("TENKHUVUC"), rs.getString("THOIGIANVAO"),rs.getString("SOTIEN")
                });
            }
            BangDL.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(TraXeJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BangDL;
    private javax.swing.JButton JBCapNhat;
    private javax.swing.JButton JBThemXe;
    private javax.swing.JButton JBTimKiem;
    private javax.swing.JButton JBTraXe;
    private javax.swing.JComboBox<String> JCBMAVEBS;
    private javax.swing.JLabel NgayRa;
    private javax.swing.JLabel Tien;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tfBienSo;
    private javax.swing.JTextField tfKhuVuc;
    private javax.swing.JTextField tfLoaiVe;
    private javax.swing.JTextField tfMaVe;
    private javax.swing.JTextField tfNgayGioVao;
    private javax.swing.JTextField tfTimKiem;
    private javax.swing.JTextField txtTien;
    // End of variables declaration//GEN-END:variables
}
